// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package loqate_bankverification.proxies;

public class AccountNumber
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject accountNumberMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Loqate_BankVerification.AccountNumber";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		AccountNumber("AccountNumber"),
		AccountNumber_Batch_Validate_v1_Request("Loqate_BankVerification.AccountNumber_Batch_Validate_v1_Request");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AccountNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Loqate_BankVerification.AccountNumber"));
	}

	protected AccountNumber(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject accountNumberMendixObject)
	{
		if (accountNumberMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Loqate_BankVerification.AccountNumber", accountNumberMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Loqate_BankVerification.AccountNumber");

		this.accountNumberMendixObject = accountNumberMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'AccountNumber.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static loqate_bankverification.proxies.AccountNumber initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return loqate_bankverification.proxies.AccountNumber.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static loqate_bankverification.proxies.AccountNumber initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new loqate_bankverification.proxies.AccountNumber(context, mendixObject);
	}

	public static loqate_bankverification.proxies.AccountNumber load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return loqate_bankverification.proxies.AccountNumber.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of AccountNumber
	 */
	public final java.lang.String getAccountNumber()
	{
		return getAccountNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of AccountNumber
	 */
	public final java.lang.String getAccountNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AccountNumber.toString());
	}

	/**
	 * Set value of AccountNumber
	 * @param accountnumber
	 */
	public final void setAccountNumber(java.lang.String accountnumber)
	{
		setAccountNumber(getContext(), accountnumber);
	}

	/**
	 * Set value of AccountNumber
	 * @param context
	 * @param accountnumber
	 */
	public final void setAccountNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String accountnumber)
	{
		getMendixObject().setValue(context, MemberNames.AccountNumber.toString(), accountnumber);
	}

	/**
	 * @return value of AccountNumber_Batch_Validate_v1_Request
	 */
	public final loqate_bankverification.proxies.Batch_Validate_v1_Request getAccountNumber_Batch_Validate_v1_Request() throws com.mendix.core.CoreException
	{
		return getAccountNumber_Batch_Validate_v1_Request(getContext());
	}

	/**
	 * @param context
	 * @return value of AccountNumber_Batch_Validate_v1_Request
	 */
	public final loqate_bankverification.proxies.Batch_Validate_v1_Request getAccountNumber_Batch_Validate_v1_Request(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		loqate_bankverification.proxies.Batch_Validate_v1_Request result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AccountNumber_Batch_Validate_v1_Request.toString());
		if (identifier != null)
			result = loqate_bankverification.proxies.Batch_Validate_v1_Request.load(context, identifier);
		return result;
	}

	/**
	 * Set value of AccountNumber_Batch_Validate_v1_Request
	 * @param accountnumber_batch_validate_v1_request
	 */
	public final void setAccountNumber_Batch_Validate_v1_Request(loqate_bankverification.proxies.Batch_Validate_v1_Request accountnumber_batch_validate_v1_request)
	{
		setAccountNumber_Batch_Validate_v1_Request(getContext(), accountnumber_batch_validate_v1_request);
	}

	/**
	 * Set value of AccountNumber_Batch_Validate_v1_Request
	 * @param context
	 * @param accountnumber_batch_validate_v1_request
	 */
	public final void setAccountNumber_Batch_Validate_v1_Request(com.mendix.systemwideinterfaces.core.IContext context, loqate_bankverification.proxies.Batch_Validate_v1_Request accountnumber_batch_validate_v1_request)
	{
		if (accountnumber_batch_validate_v1_request == null)
			getMendixObject().setValue(context, MemberNames.AccountNumber_Batch_Validate_v1_Request.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.AccountNumber_Batch_Validate_v1_Request.toString(), accountnumber_batch_validate_v1_request.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return accountNumberMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final loqate_bankverification.proxies.AccountNumber that = (loqate_bankverification.proxies.AccountNumber) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Loqate_BankVerification.AccountNumber";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
