// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package loqate_bankverification.proxies;

public class Interactive_Validate_v2_Request extends loqate_bankverification.proxies.Request
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Loqate_BankVerification.Interactive_Validate_v2_Request";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		AccountNumber("AccountNumber"),
		SortCode("SortCode"),
		Key("Key");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Interactive_Validate_v2_Request(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Loqate_BankVerification.Interactive_Validate_v2_Request"));
	}

	protected Interactive_Validate_v2_Request(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject interactive_Validate_v2_RequestMendixObject)
	{
		super(context, interactive_Validate_v2_RequestMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("Loqate_BankVerification.Interactive_Validate_v2_Request", interactive_Validate_v2_RequestMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Loqate_BankVerification.Interactive_Validate_v2_Request");
	}

	/**
	 * @deprecated Use 'Interactive_Validate_v2_Request.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static loqate_bankverification.proxies.Interactive_Validate_v2_Request initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return loqate_bankverification.proxies.Interactive_Validate_v2_Request.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static loqate_bankverification.proxies.Interactive_Validate_v2_Request initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new loqate_bankverification.proxies.Interactive_Validate_v2_Request(context, mendixObject);
	}

	public static loqate_bankverification.proxies.Interactive_Validate_v2_Request load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return loqate_bankverification.proxies.Interactive_Validate_v2_Request.initialize(context, mendixObject);
	}

	/**
	 * @return value of AccountNumber
	 */
	public final java.lang.String getAccountNumber()
	{
		return getAccountNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of AccountNumber
	 */
	public final java.lang.String getAccountNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AccountNumber.toString());
	}

	/**
	 * Set value of AccountNumber
	 * @param accountnumber
	 */
	public final void setAccountNumber(java.lang.String accountnumber)
	{
		setAccountNumber(getContext(), accountnumber);
	}

	/**
	 * Set value of AccountNumber
	 * @param context
	 * @param accountnumber
	 */
	public final void setAccountNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String accountnumber)
	{
		getMendixObject().setValue(context, MemberNames.AccountNumber.toString(), accountnumber);
	}

	/**
	 * @return value of SortCode
	 */
	public final java.lang.String getSortCode()
	{
		return getSortCode(getContext());
	}

	/**
	 * @param context
	 * @return value of SortCode
	 */
	public final java.lang.String getSortCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SortCode.toString());
	}

	/**
	 * Set value of SortCode
	 * @param sortcode
	 */
	public final void setSortCode(java.lang.String sortcode)
	{
		setSortCode(getContext(), sortcode);
	}

	/**
	 * Set value of SortCode
	 * @param context
	 * @param sortcode
	 */
	public final void setSortCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sortcode)
	{
		getMendixObject().setValue(context, MemberNames.SortCode.toString(), sortcode);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final loqate_bankverification.proxies.Interactive_Validate_v2_Request that = (loqate_bankverification.proxies.Interactive_Validate_v2_Request) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Loqate_BankVerification.Interactive_Validate_v2_Request";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
