// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package loqate_bankverification.proxies;

public class SortCode
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject sortCodeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Loqate_BankVerification.SortCode";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		SortCode("SortCode"),
		SortCode_Batch_Validate_v1_Request_2("Loqate_BankVerification.SortCode_Batch_Validate_v1_Request_2");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SortCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Loqate_BankVerification.SortCode"));
	}

	protected SortCode(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject sortCodeMendixObject)
	{
		if (sortCodeMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Loqate_BankVerification.SortCode", sortCodeMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Loqate_BankVerification.SortCode");

		this.sortCodeMendixObject = sortCodeMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'SortCode.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static loqate_bankverification.proxies.SortCode initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return loqate_bankverification.proxies.SortCode.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static loqate_bankverification.proxies.SortCode initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new loqate_bankverification.proxies.SortCode(context, mendixObject);
	}

	public static loqate_bankverification.proxies.SortCode load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return loqate_bankverification.proxies.SortCode.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of SortCode
	 */
	public final java.lang.String getSortCode()
	{
		return getSortCode(getContext());
	}

	/**
	 * @param context
	 * @return value of SortCode
	 */
	public final java.lang.String getSortCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SortCode.toString());
	}

	/**
	 * Set value of SortCode
	 * @param sortcode
	 */
	public final void setSortCode(java.lang.String sortcode)
	{
		setSortCode(getContext(), sortcode);
	}

	/**
	 * Set value of SortCode
	 * @param context
	 * @param sortcode
	 */
	public final void setSortCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sortcode)
	{
		getMendixObject().setValue(context, MemberNames.SortCode.toString(), sortcode);
	}

	/**
	 * @return value of SortCode_Batch_Validate_v1_Request_2
	 */
	public final loqate_bankverification.proxies.Batch_Validate_v1_Request getSortCode_Batch_Validate_v1_Request_2() throws com.mendix.core.CoreException
	{
		return getSortCode_Batch_Validate_v1_Request_2(getContext());
	}

	/**
	 * @param context
	 * @return value of SortCode_Batch_Validate_v1_Request_2
	 */
	public final loqate_bankverification.proxies.Batch_Validate_v1_Request getSortCode_Batch_Validate_v1_Request_2(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		loqate_bankverification.proxies.Batch_Validate_v1_Request result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SortCode_Batch_Validate_v1_Request_2.toString());
		if (identifier != null)
			result = loqate_bankverification.proxies.Batch_Validate_v1_Request.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SortCode_Batch_Validate_v1_Request_2
	 * @param sortcode_batch_validate_v1_request_2
	 */
	public final void setSortCode_Batch_Validate_v1_Request_2(loqate_bankverification.proxies.Batch_Validate_v1_Request sortcode_batch_validate_v1_request_2)
	{
		setSortCode_Batch_Validate_v1_Request_2(getContext(), sortcode_batch_validate_v1_request_2);
	}

	/**
	 * Set value of SortCode_Batch_Validate_v1_Request_2
	 * @param context
	 * @param sortcode_batch_validate_v1_request_2
	 */
	public final void setSortCode_Batch_Validate_v1_Request_2(com.mendix.systemwideinterfaces.core.IContext context, loqate_bankverification.proxies.Batch_Validate_v1_Request sortcode_batch_validate_v1_request_2)
	{
		if (sortcode_batch_validate_v1_request_2 == null)
			getMendixObject().setValue(context, MemberNames.SortCode_Batch_Validate_v1_Request_2.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SortCode_Batch_Validate_v1_Request_2.toString(), sortcode_batch_validate_v1_request_2.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return sortCodeMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final loqate_bankverification.proxies.SortCode that = (loqate_bankverification.proxies.SortCode) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Loqate_BankVerification.SortCode";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
